version: '3.2'

services:

  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_USER= root
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=complaintDB
    ports:
      - 9011:3306
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
